function [GRsimple,GRfull] = GR_analytical(r0, IC, rl)
%note Deff = D/alpha corrected for density


GRsimple = r0 .* log(1/2 * rl .*IC .* (1+sqrt(1 + 8 ./ (rl .* IC))) ...
    + 4);

GRfull = r0 .* log(... 
          ( (IC-4) .* ( rl .* (IC+2) + sqrt((IC-2).^2 .* rl.^2 + 8*IC.*rl)) + 8*IC)...
          ./...
          (2*(IC.*(1+rl) - 4*rl)));
    
      
%       
% 
% GRsimple = r0 .* log(1/2 * rl .*IC .* (1+sqrt(1 + (8 * mu)  ./ (rl .* IC)))./mu ...
%     + 4);
% 
% GRfull = r0 .* log(... 
%           ( (IC-4) .* ( rl .* (IC+2) + sqrt((IC+2).^2 .* rl.^2 + 8*IC.*rl.*mu)) + 8*IC.*(rl+mu))...
%           ./...
%           (2*(IC.*(mu + 2*rl) - 4*rl)));
%           