[exGridE1,exGridE2,numIt,errorCode] = SteadyState_3D_SOR_Solver_CoreC(...
    exGridE1,exGridE2, extendedGridType,...
    int32(gridSizeScaled), dx, boundaryType,...
    ru1 ,ru2, rl1, rl2, D1, D2, Iconst1, Iconst2, alpha,...
    tolerance, omega);