
toDoList = {...
    %'RunModel_Fig3cd';...
    'RunModel_Fig4b';...
    'RunModel_Fig4c_FigS9';...
    'RunModel_Fig5d';...
    'RunModel_Fig5e';...
    'RunModel_FigS3';...
    'RunModel_FigS5';...
    'RunModel_FigS8'};



for tt = 1:length(toDoList)
    try
        fprintf('Starting with %s\n',toDoList{tt})
        eval(toDoList{tt})
        fprintf('++Succes with %s\n',toDoList{tt})
    catch
        warning('--Failed %s',toDoList{tt})
    end
end